/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const User = IDL.Record({
  'id' : IDL.Text,
  'dob' : IDL.Text,
  'pan' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'createdAt' : Time,
  'role' : IDL.Text,
  'aadhaar' : IDL.Text,
  'email' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'isVerified' : IDL.Bool,
  'fatherName' : IDL.Text,
  'address' : IDL.Text,
  'nomineeRelation' : IDL.Text,
  'gender' : IDL.Text,
  'nomineeName' : IDL.Text,
  'passwordHash' : IDL.Text,
  'mobile' : IDL.Text,
  'pincode' : IDL.Text,
});
export const Application = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'applicantName' : IDL.Text,
  'applicantPhone' : IDL.Text,
  'data' : IDL.Text,
  'createdAt' : Time,
  'adminRemark' : IDL.Text,
  'applicantEmail' : IDL.Text,
  'applicationType' : IDL.Text,
});
export const KycRecord = IDL.Record({
  'remark' : IDL.Text,
  'status' : IDL.Text,
  'bankDetails' : IDL.Text,
  'userId' : IDL.Text,
  'updatedAt' : Time,
  'photo' : IDL.Text,
  'addressProof' : IDL.Text,
  'panDoc' : IDL.Text,
  'aadhaarDoc' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'isApproved' : IDL.Bool,
  'createdAt' : Time,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'approveReview' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createUser' : IDL.Func([User], [IDL.Text], []),
  'deleteReview' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getAllContent' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllKyc' : IDL.Func([], [IDL.Vec(KycRecord)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getApplication' : IDL.Func([IDL.Text], [IDL.Opt(Application)], ['query']),
  'getContent' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getKyc' : IDL.Func([IDL.Text], [IDL.Opt(KycRecord)], ['query']),
  'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'saveContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveKyc' : IDL.Func([KycRecord], [], []),
  'submitApplication' : IDL.Func([Application], [IDL.Text], []),
  'submitReview' : IDL.Func([Review], [IDL.Text], []),
  'updateApplicationStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateKycStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateUser' : IDL.Func([IDL.Text, User], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const User = IDL.Record({
    'id' : IDL.Text,
    'dob' : IDL.Text,
    'pan' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'createdAt' : Time,
    'role' : IDL.Text,
    'aadhaar' : IDL.Text,
    'email' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'isVerified' : IDL.Bool,
    'fatherName' : IDL.Text,
    'address' : IDL.Text,
    'nomineeRelation' : IDL.Text,
    'gender' : IDL.Text,
    'nomineeName' : IDL.Text,
    'passwordHash' : IDL.Text,
    'mobile' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const Application = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'applicantName' : IDL.Text,
    'applicantPhone' : IDL.Text,
    'data' : IDL.Text,
    'createdAt' : Time,
    'adminRemark' : IDL.Text,
    'applicantEmail' : IDL.Text,
    'applicationType' : IDL.Text,
  });
  const KycRecord = IDL.Record({
    'remark' : IDL.Text,
    'status' : IDL.Text,
    'bankDetails' : IDL.Text,
    'userId' : IDL.Text,
    'updatedAt' : Time,
    'photo' : IDL.Text,
    'addressProof' : IDL.Text,
    'panDoc' : IDL.Text,
    'aadhaarDoc' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'isApproved' : IDL.Bool,
    'createdAt' : Time,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'approveReview' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createUser' : IDL.Func([User], [IDL.Text], []),
    'deleteReview' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getAllContent' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllKyc' : IDL.Func([], [IDL.Vec(KycRecord)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getApplication' : IDL.Func([IDL.Text], [IDL.Opt(Application)], ['query']),
    'getContent' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getKyc' : IDL.Func([IDL.Text], [IDL.Opt(KycRecord)], ['query']),
    'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'saveContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveKyc' : IDL.Func([KycRecord], [], []),
    'submitApplication' : IDL.Func([Application], [IDL.Text], []),
    'submitReview' : IDL.Func([Review], [IDL.Text], []),
    'updateApplicationStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateKycStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateUser' : IDL.Func([IDL.Text, User], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };