/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : string,
  'status' : string,
  'applicantName' : string,
  'applicantPhone' : string,
  'data' : string,
  'createdAt' : Time,
  'adminRemark' : string,
  'applicantEmail' : string,
  'applicationType' : string,
}
export interface KycRecord {
  'remark' : string,
  'status' : string,
  'bankDetails' : string,
  'userId' : string,
  'updatedAt' : Time,
  'photo' : string,
  'addressProof' : string,
  'panDoc' : string,
  'aadhaarDoc' : string,
}
export interface Review {
  'id' : string,
  'isApproved' : boolean,
  'createdAt' : Time,
  'reviewerName' : string,
  'comment' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface User {
  'id' : string,
  'dob' : string,
  'pan' : string,
  'status' : string,
  'name' : string,
  'designation' : string,
  'createdAt' : Time,
  'role' : string,
  'aadhaar' : string,
  'email' : string,
  'district' : string,
  'state' : string,
  'isVerified' : boolean,
  'fatherName' : string,
  'address' : string,
  'nomineeRelation' : string,
  'gender' : string,
  'nomineeName' : string,
  'passwordHash' : string,
  'mobile' : string,
  'pincode' : string,
}
export interface _SERVICE {
  'approveReview' : ActorMethod<[string], boolean>,
  'createUser' : ActorMethod<[User], string>,
  'deleteReview' : ActorMethod<[string], boolean>,
  'deleteUser' : ActorMethod<[string], boolean>,
  'getAllApplications' : ActorMethod<[], Array<Application>>,
  'getAllContent' : ActorMethod<[], Array<[string, string]>>,
  'getAllKyc' : ActorMethod<[], Array<KycRecord>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getApplication' : ActorMethod<[string], [] | [Application]>,
  'getContent' : ActorMethod<[string], [] | [string]>,
  'getKyc' : ActorMethod<[string], [] | [KycRecord]>,
  'getUser' : ActorMethod<[string], [] | [User]>,
  'getUserByEmail' : ActorMethod<[string], [] | [User]>,
  'saveContent' : ActorMethod<[string, string], undefined>,
  'saveKyc' : ActorMethod<[KycRecord], undefined>,
  'submitApplication' : ActorMethod<[Application], string>,
  'submitReview' : ActorMethod<[Review], string>,
  'updateApplicationStatus' : ActorMethod<[string, string, string], boolean>,
  'updateKycStatus' : ActorMethod<[string, string, string], boolean>,
  'updateUser' : ActorMethod<[string, User], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];